<script setup lang="ts">
import { onMounted,ref } from 'vue'
import { useRoute } from 'vue-router'
import { getConversation,getInvocation,getInvocations,getMessages } from '../api/admin'
import type { Conversation,InvocationDetail,InvocationSummary,Message } from '../types/admin'
import JsonPayloadViewer from '../components/JsonPayloadViewer.vue'
const id=String(useRoute().params.id),conversation=ref<Conversation>(),messages=ref<Message[]>([]),invocations=ref<InvocationSummary[]>([]),detail=ref<InvocationDetail>(),dialog=ref(false),loading=ref(false)
async function load(){loading.value=true;try{[conversation.value,messages.value,invocations.value]=await Promise.all([getConversation(id),getMessages(id),getInvocations(id)])}finally{loading.value=false}}
async function open(item:InvocationSummary){detail.value=await getInvocation(item.id);dialog.value=true} const fmt=(v?:string)=>v?new Date(v).toLocaleString():'—'
onMounted(load)
</script>
<template><div v-loading="loading"><el-page-header @back="$router.back()"><template #content><span>对话详情</span></template></el-page-header><p class="page-subtitle mono">{{conversation?.sessionId}} · {{conversation?.botId}} · {{conversation?.internalUserId}}</p><el-row :gutter="18"><el-col :span="12"><section class="panel"><h2>消息时间线</h2><el-timeline><el-timeline-item v-for="m in messages" :key="m.id" :timestamp="fmt(m.createTime)" :type="m.errorMsg?'danger':m.messageType===0?'primary':'success'"><div class="message"><strong>{{m.messageType===0?'用户':'助手'}}</strong><span v-if="m.responseTime" class="muted">{{m.responseTime}} ms</span><p>{{m.content||m.errorMsg||'（空消息）'}}</p><details v-if="m.reasoningContent"><summary>推理内容</summary><pre>{{m.reasoningContent}}</pre></details></div></el-timeline-item></el-timeline></section></el-col><el-col :span="12"><section class="panel"><h2>模型调用链</h2><el-empty v-if="!invocations.length" description="该对话暂无审计记录"/><div v-for="item in invocations" :key="item.id" class="call" @click="open(item)"><div><el-tag :type="item.status==='SUCCESS'?'success':'danger'" size="small">{{item.status}}</el-tag><strong>{{item.sequenceNo}}. {{item.invocationType}}</strong></div><span>{{item.model||item.provider||'未知模型'}} · {{item.durationMs??'—'}} ms</span><small>{{fmt(item.startedAt)}}</small><p v-if="item.errorMessage">{{item.errorMessage}}</p></div></section></el-col></el-row><el-dialog v-model="dialog" width="84%" top="5vh" title="模型调用详情"><el-descriptions v-if="detail" :column="4" border><el-descriptions-item label="类型">{{detail.invocationType}}</el-descriptions-item><el-descriptions-item label="模型">{{detail.model}}</el-descriptions-item><el-descriptions-item label="耗时">{{detail.durationMs}} ms</el-descriptions-item><el-descriptions-item label="Token">{{detail.inputTokens??'—'}} / {{detail.outputTokens??'—'}}</el-descriptions-item></el-descriptions><el-tabs v-if="detail" class="tabs"><el-tab-pane label="原始请求"><JsonPayloadViewer :value="detail.requestPayload"/></el-tab-pane><el-tab-pane label="原始响应"><JsonPayloadViewer :value="detail.responsePayload"/></el-tab-pane><el-tab-pane label="工具调用"><JsonPayloadViewer :value="detail.toolCallsJson"/></el-tab-pane><el-tab-pane label="错误"><pre class="payload">{{detail.errorType}}\n{{detail.errorMessage}}</pre></el-tab-pane></el-tabs></el-dialog></div></template>
<style scoped>h2{font-size:17px;margin:0 0 22px}.message{background:#f8fafc;border-radius:10px;padding:12px}.message strong{margin-right:10px}.message p{white-space:pre-wrap;line-height:1.6}.call{padding:14px;border:1px solid #eaecf0;border-radius:10px;margin-bottom:10px;cursor:pointer;transition:.15s}.call:hover{border-color:#7f56d9;box-shadow:0 4px 12px rgba(127,86,217,.1)}.call strong{margin-left:8px}.call span,.call small{display:block;color:#667085;margin-top:8px}.call p{color:#d92d20}.tabs{margin-top:18px}</style>
