export interface Overview { botCount:number; onlineBotCount:number; waitingQrBotCount:number; errorBotCount:number; todayConversationCount:number; todayMessageCount:number; todayInvocationCount:number; todayFailedInvocationCount:number; generatedAt:string }
export interface BotStatus { tenantId:string; botId:string; displayName:string; channel:string; configuredStatus:string; runtimeStatus:string; connectedAt?:string; statusChangedAt?:string; lastPollAt?:string; lastMessageAt?:string; lastErrorAt?:string; lastError?:string; reconnectAttempts:number; resumeContextAvailable:boolean }
export interface Conversation { id:string; tenantId:string; botId:string; sessionId:string; username?:string; internalUserId:string; channel:string; active:boolean; messageCount:number; lastMessageTime?:string; createdTime:string; updatedTime:string }
export interface Message { id:string; tenantId:string; conversationId:string; sessionId:string; messageType:number; content?:string; reasoningContent?:string; messageSeq:number; responseTime?:number; errorMsg?:string; createTime:string; updateTime:string }
export interface InvocationSummary { id:string; tenantId:string; botId?:string; conversationId?:string; sessionId?:string; traceId:string; sequenceNo:number; invocationType:string; provider?:string; model?:string; status:string; inputTokens?:number; outputTokens?:number; durationMs?:number; errorMessage?:string; startedAt:string; completedAt?:string }
export interface InvocationDetail extends InvocationSummary { parentInvocationId?:string; requestPayload?:string; responsePayload?:string; toolCallsJson?:string; requestTruncated:boolean; responseTruncated:boolean; requestOriginalLength?:number; responseOriginalLength?:number; requestSha256?:string; responseSha256?:string; errorType?:string }
export interface PageResult<T> { content:T[]; totalElements:number; totalPages:number; number:number; size:number }
export interface InviteCode { id:number; code:string; status:string; quota:number|null; usedCount:number; expiresAt:string|null; remark?:string; createdBy?:string; createdAt:string }
export interface GenerateInviteCodesRequest { count:number; quota?:number|null; expiresAt?:string|null; remark?:string }
export interface AdminLoginResult { sessionToken:string; expiresAt:string; username:string; role:string }
