package com.dust.wxclawbackfront.ai.document;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * 文档生成器
 * 将长文本生成为 txt 或 markdown 文档
 */
@Slf4j
@Component
public class DocumentGenerator {

    private static final int TEXT_THRESHOLD = 500; // 超过500字生成文档

    /**
     * 检查是否需要生成文档
     */
    public boolean shouldGenerateDocument(String text) {
        return text != null && text.length() > TEXT_THRESHOLD;
    }

    /**
     * 生成文档
     * @param content 文本内容
     * @param format 文档格式：txt 或 markdown
     * @return 文档结果
     */
    public DocumentResult generate(String content, String format) {
        if (content == null || content.isBlank()) {
            return new DocumentResult(null, null, null, "内容为空");
        }

        boolean isMarkdown = "markdown".equalsIgnoreCase(format) || "md".equalsIgnoreCase(format);
        String fileExtension = isMarkdown ? "md" : "txt";
        String formattedContent = isMarkdown ? formatAsMarkdown(content) : content;
        String fileName = generateFileName(formattedContent, fileExtension);

        byte[] bytes = formattedContent.getBytes(StandardCharsets.UTF_8);
        String contentType = isMarkdown ? "text/markdown" : "text/plain";

        log.info("生成文档: fileName={}, format={}, size={}bytes", fileName, format, bytes.length);

        return new DocumentResult(fileName, bytes, contentType, null);
    }

    /**
     * 格式化为 Markdown
     */
    private String formatAsMarkdown(String content) {
        // 清理 AI 回复中的代码块标记
        String cleanedContent = cleanCodeBlockMarkers(content);

        StringBuilder sb = new StringBuilder();

        // 添加文档头
        sb.append("# AI 对话回复\n\n");
        sb.append("---\n\n");

        // 处理内容，保留原有的换行和格式
        String[] lines = cleanedContent.split("\n");
        for (String line : lines) {
            String trimmed = line.trim();

            // 如果已经是 markdown 标题格式，保持原样
            if (trimmed.startsWith("#")) {
                sb.append(line).append("\n");
            }
            // 如果是列表项，保持原样
            else if (trimmed.startsWith("- ") || trimmed.startsWith("* ") || trimmed.startsWith("• ")) {
                sb.append(line).append("\n");
            }
            // 如果是数字列表，保持原样
            else if (trimmed.matches("^\\d+[.、].*")) {
                sb.append(line).append("\n");
            }
            // 空行保持
            else if (trimmed.isEmpty()) {
                sb.append("\n");
            }
            // 普通文本，添加段落格式
            else {
                sb.append(line).append("\n\n");
            }
        }

        // 添加文档尾
        sb.append("\n---\n");
        sb.append("*Generated by WX-Claw AI*\n");

        return sb.toString();
    }

    /**
     * 清理 AI 回复中的代码块标记
     * 例如：```markdown ... ``` 或 ``` ... ```
     */
    private String cleanCodeBlockMarkers(String content) {
        if (content == null) {
            return "";
        }

        String result = content.trim();

        // 移除开头的 ```markdown 或 ```text 或 ```
        if (result.startsWith("```markdown")) {
            result = result.substring("```markdown".length());
        } else if (result.startsWith("```text")) {
            result = result.substring("```text".length());
        } else if (result.startsWith("```")) {
            result = result.substring("```".length());
        }
        result = result.trim();

        // 移除结尾的 ```
        if (result.endsWith("```")) {
            result = result.substring(0, result.length() - 3);
        }
        result = result.trim();

        return result;
    }

    /**
     * 生成文件名 - 根据内容自动提取标题
     */
    private String generateFileName(String content, String extension) {
        // 尝试从内容中提取标题
        String title = extractTitle(content);
        
        if (title != null && !title.isBlank()) {
            // 清理标题，移除特殊字符
            String cleanTitle = title.replaceAll("[\\\\/:*?\"<>|\\s]+", "_")
                    .replaceAll("_+", "_")
                    .replaceAll("^_|_$", "");
            
            // 限制长度
            if (cleanTitle.length() > 30) {
                cleanTitle = cleanTitle.substring(0, 30);
            }
            
            if (!cleanTitle.isBlank()) {
                return cleanTitle + "." + extension;
            }
        }
        
        // 如果无法提取标题，使用时间戳
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        return "ai_reply_" + timestamp + "." + extension;
    }

    /**
     * 从内容中提取标题
     */
    private String extractTitle(String content) {
        if (content == null || content.isBlank()) {
            return null;
        }

        String[] lines = content.split("\n");
        for (String line : lines) {
            String trimmed = line.trim();
            
            // 跳过空行
            if (trimmed.isEmpty()) {
                continue;
            }
            
            // 提取 markdown 标题（# 开头）
            if (trimmed.startsWith("# ")) {
                return trimmed.substring(2).trim();
            }
            if (trimmed.startsWith("## ")) {
                return trimmed.substring(3).trim();
            }
            
            // 提取《》中的内容
            if (trimmed.contains("《") && trimmed.contains("》")) {
                int start = trimmed.indexOf("《");
                int end = trimmed.indexOf("》");
                if (end > start) {
                    return trimmed.substring(start + 1, end);
                }
            }
            
            // 如果第一行不为空且长度合适，作为标题
            if (trimmed.length() >= 3 && trimmed.length() <= 50) {
                return trimmed;
            }
        }
        
        return null;
    }

    /**
     * 文档结果
     */
    public record DocumentResult(String fileName, byte[] bytes, String contentType, String error) {
        public boolean isSuccess() {
            return error == null && bytes != null && bytes.length > 0;
        }
    }
}
